import images from '../assets/images/index.js';

export const products = [
  {
    id: 1,
    name: 'Silk Wrap Dress',
    category: 'Dresses',
    price: 1499,
    originalPrice: 1999,
    image: images.silkWrapDress,
    hoverImage: images.silkWrapDress,
    colors: ['#c9a98a', '#6da9b5', '#1a1a1a'],
    rating: 4,
    reviews: 128,
    isNewArrival: false,
  },
  {
    id: 2,
    name: 'Linen Blazer Set',
    category: 'Blazers',
    price: 2499,
    originalPrice: null,
    image: images.linenBlazerSet,
    hoverImage: images.linenBlazerSet,
    colors: ['#f0ebe4', '#8b7355', '#1a1a1a'],
    rating: 5,
    reviews: 64,
    isNewArrival: true,
  },
  {
    id: 3,
    name: 'Floral Maxi Skirt',
    category: 'Skirts',
    price: 999,
    originalPrice: 1299,
    image: images.floralMaxiSkirt,
    hoverImage: images.floralMaxiSkirt,
    colors: ['#e8f4f7', '#d4a5a5', '#6da9b5'],
    rating: 4,
    reviews: 95,
    isNewArrival: false,
  },
  {
    id: 4,
    name: 'Cashmere Sweater',
    category: 'Tops',
    price: 1799,
    originalPrice: null,
    image: images.cashmereSweater,
    hoverImage: images.cashmereSweater,
    colors: ['#c9a98a', '#e8d5b7', '#6da9b5'],
    rating: 5,
    reviews: 203,
    isNewArrival: true,
  },
  {
    id: 5,
    name: 'Tailored Trousers',
    category: 'Bottoms',
    price: 1299,
    originalPrice: 1699,
    image: images.tailoredTrousers,
    hoverImage: images.tailoredTrousers,
    colors: ['#1a1a1a', '#5b5b5b', '#f0ebe4'],
    rating: 4,
    reviews: 77,
    isNewArrival: false,
  },
  {
    id: 6,
    name: 'Satin Slip Dress',
    category: 'Dresses',
    price: 1899,
    originalPrice: null,
    image: images.satinSlipDress,
    hoverImage: images.satinSlipDress,
    colors: ['#c9a98a', '#1a1a1a', '#6da9b5'],
    rating: 5,
    reviews: 141,
    isNewArrival: true,
  },
  {
    id: 7,
    name: 'Cropped Denim Jacket',
    category: 'Jackets',
    price: 1499,
    originalPrice: 1999,
    image: images.croppedDenimJacket,
    hoverImage: images.croppedDenimJacket,
    colors: ['#4a6b8a', '#8899aa', '#1a1a1a'],
    rating: 4,
    reviews: 89,
    isNewArrival: false,
  },
  {
    id: 8,
    name: 'Ruffle Blouse',
    category: 'Tops',
    price: 799,
    originalPrice: 1099,
    image: images.ruffleBlouse,
    hoverImage: images.ruffleBlouse,
    colors: ['#fff', '#f0ebe4', '#6da9b5'],
    rating: 4,
    reviews: 52,
    isNewArrival: false,
  },
];

export const categories = [
  {
    id: 1,
    name: 'Dresses',
    count: 45,
    image: images.silkWrapDress,
  },
  {
    id: 2,
    name: 'Tops & Blouses',
    count: 62,
    image: images.cashmereSweater,
  },
  {
    id: 3,
    name: 'Bottoms',
    count: 38,
    image: images.floralMaxiSkirt,
  },
  {
    id: 4,
    name: 'Outerwear',
    count: 27,
    image: images.croppedDenimJacket,
  },
];
